# Generated by Django 5.1.5 on 2025-01-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='hashed_data',
            new_name='encrypted_data',
        ),
    ]
