# Generated by Django 5.1.5 on 2025-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_rename_hashed_data_userdata_encrypted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='hashed_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
