# Generated by Django 5.1.5 on 2025-01-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0004_rawuserdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawuserdata',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
