# Generated by Django 5.1.5 on 2025-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0005_alter_rawuserdata_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
